name: React app deployement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'cutesthypnotist'
        reponame: 'Discord-Sticker-Downloader'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
